# These are supported funding model platforms

github: ToastHawaii
custom:
  [
    paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JFWXTYPKBD2YA&source=url,
    creators.brave.com/c/DOetbSqf6o,
  ]
