defaults:
  - scope:
      path: "docs/README.md"
    values:
      lang: "en"
      title: "OSM Apps"
      description: "Experience the world in a creative, productive and unexpected way."
      base: "/"
