import { equalsIgnoreCase } from "./utilities/string";

const languages: {
  code: string;
  display: string;
}[] = [
  { code: "af", display: "Afrikaans" },
  { code: "ar", display: "العربية" },
  { code: "ast", display: "asturianu" },
  { code: "az", display: "azərbaycanca" },
  { code: "be", display: "беларуская" },
  { code: "bg", display: "български" },
  { code: "bn", display: "বাংলা" },
  { code: "br", display: "brezhoneg" },
  { code: "bs", display: "bosanski" },
  { code: "ca", display: "català" },
  { code: "cs", display: "čeština" },
  { code: "da", display: "dansk" },
  { code: "de", display: "Deutsch" },
  { code: "diq", display: "Zazaki" },
  { code: "el", display: "Ελληνικά" },
  { code: "en", display: "English" },
  { code: "eo", display: "Esperanto" },
  { code: "es", display: "español" },
  { code: "et", display: "eesti" },
  { code: "eu", display: "euskara" },
  { code: "fa", display: "فارسی" },
  { code: "fi", display: "suomi" },
  { code: "fr", display: "français" },
  { code: "fy", display: "Frysk" },
  { code: "gcf", display: "kréyòl gwadloupéyen" },
  { code: "gl", display: "galego" },
  { code: "he", display: "עברית" },
  { code: "hr", display: "hrvatski" },
  { code: "ht", display: "Kreyòl ayisyen" },
  { code: "hu", display: "magyar" },
  { code: "hy", display: "հայերեն" },
  { code: "ia", display: "interlingua" },
  { code: "id", display: "Bahasa Indonesia" },
  { code: "is", display: "íslenska" },
  { code: "it", display: "italiano" },
  { code: "ja", display: "日本語" },
  { code: "ka", display: "ქართული" },
  { code: "ko", display: "한국어" },
  { code: "ku", display: "kurdî" },
  { code: "lb", display: "Lëtzebuergesch" },
  { code: "lt", display: "lietuvių" },
  { code: "lv", display: "latviešu" },
  { code: "mk", display: "македонски" },
  { code: "ml", display: "മലയാളം" },
  { code: "mn", display: "монгол" },
  { code: "ms", display: "Bahasa Melayu" },
  { code: "mul", display: "Multilingual" }
  { code: "my", display: "မြန်မာဘာသာ" },
  { code: "ne", display: "नेपाली" },
  { code: "nl", display: "Nederlands" },
  { code: "nn", display: "norsk nynorsk" },
  { code: "no", display: "norsk" },
  { code: "oc", display: "occitan" },
  { code: "pl", display: "polski" },
  { code: "ps", display: "پښتو" },
  { code: "pt", display: "português" },
  { code: "ro", display: "română" },
  { code: "ru", display: "русский" },
  { code: "si", display: "සිංහල" },
  { code: "sk", display: "slovenčina" },
  { code: "sl", display: "slovenščina" },
  { code: "sq", display: "shqip" },
  { code: "sr-latn", display: "srpski (latinica)" },
  { code: "sr", display: "српски / srpski" },
  { code: "sv", display: "svenska" },
  { code: "ta", display: "தமிழ்" },
  { code: "th", display: "ไทย" },
  { code: "tl", display: "Tagalog" },
  { code: "tr", display: "Türkçe" },
  { code: "tzm", display: "ⵜⴰⵎⴰⵣⵉⵖⵜ" },
  { code: "uk", display: "українська" },
  { code: "vi", display: "Tiếng Việt" },
  { code: "yue", display: "粵語" },
  { code: "zh-hans", display: "中文（简体）" },
  { code: "zh-hant", display: "中文（繁體）" },

];

export function languageValueToDisplay(value: string) {
  for (const language of languages) {
    if (equalsIgnoreCase(language.code, value)) return language.display;
  }
  return value;
}
